version: "3"
services:
  client:
    image: "ruffwise/multi-client"
    mem_limit: 128m
    hostname: client

  server:
    image: "ruffwise/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  worker:
    image: "ruffwise/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    image: "ruffwise/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
